config/routes.rb
Rails.application.routes.draw do

  devise_for :user

  get '/dashboard' => 'users#dashboard', :as => :dashboard

  resources :restaurants do
  	resources :reservations, :only => [:new, :create]
  end

  resources :reservations, :except => [:new, :create]

  root :to => 'restaurants#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	validates :name, presence: true
	
	has_many :restaurants, dependent: :destroy    
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant

	after_create :send_notification

	after_initialize :defaults

	def defaults
    self.status ||= 'pending'
  end

	def send_notification
		ReservationMailer.new_reservation(self).deliver
	end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true,
                    length: { minimum: 3 }

	validates :name, :description, :full_address, :phone_number, presence: true 

	belongs_to :user
	has_many :reservations

	accepts_nested_attributes_for :reservations        
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	validates :name, presence: true
	validates :role, inclusion: { in: ["owner", "patron"] }
	
	has_many :restaurants, dependent: :destroy    

	def owner?
		role == "owner"
	end

	def patron?
		role == "patron"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	before_action :configure_permitted_parameters, if: :devise_controller?

  	protected

  	def configure_permitted_parameters
    	devise_parameter_sanitizer.for(:sign_up) << :name
    	devise_parameter_sanitizer.for(:account_update) << :name
  	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  #before_action :load_restaurant, :except => [:index, :show, :edit]
  before_action :authenticate_user!, only: [:destroy]


	def index
		@restaurant = Restaurant.find(params[:restaurant_id])
		@reservations = @restaurant.reservations
  end

	def create
    @restaurant = Restaurant.find(params[:restaurant_id])
		@reservation = @restaurant.reservations.build(reservations_params)
    if @reservation.save
      redirect_to root_path, notice: "Booked table at #{@restaurant.name}"
    else
      render :new
    end
  end

	def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.find(params[:id])

    if @reservation.update(reservations_params)
      redirect_to restaurant_reservation_path(@restaurant, @reservation)
    else
      render :edit
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to @restaurant
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.find(params[:id])
  end

	private

  #def load_restaurant
  #  @restaurant = Restaurant.find(params[:restaurant_id])
  #end

  def reservations_params
    params.require(:reservation).permit(:email, :request_time, :message, :status)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	before_filter :check_user, only: [:edit, :update, :destroy]

	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new
    @reservation.restaurant = @restaurant
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		@restaurant.user_id = current_user.id

		if @restaurant.save 
			flash[:notice] = "Restaurant #{@restaurant.name} successfully Created"
		redirect_to @restaurant
		else
			render :new
		end
	end

	def edit
		3.times { @restaurant.reservations.build }
	end

	def update
		
		if @restaurant.update(restaurant_params)
			redirect_to @restaurant
		else
			render :edit
		end
	end

	def destroy
		@restaurant.destroy
		redirect_to restaurants_path
	end

	private
		def restaurant_params
			params.require(:restaurant).permit(:name, :description, :full_address, :phone_number, 
				reservations_attributes:[:id, :status])

		end

		def check_user
			@restaurant = Restaurant.find(params[:id])
			if current_user != @restaurant.user
				redirect_to root_url
			end	
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  before_filter :authenticate_user!
   
  def dashboard
    @user = current_user
    @restaurants = current_user.restaurants
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if user_signed_in? %>
		<%= link_to "Edit Profile", edit_user_registration_path %>
		<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Sign Up", new_user_registration_path %>
		<%= link_to "Log In", new_user_session_path %>
	<% end %>

	
	</p>

<% flash.each do |name, message| %>
	<div class="<%= name %>"><%= message %></div>
<% end %>
	
<%= yield %>

</body>
</html>

app/views/owners/dashboard.html.erb
<h1> <%= @owner.name %> Dashboard </h1>
  <l> <%= link_to 'Add Restaurant', new_restaurant_path %>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  <%- @restaurants.each do |restaurant| %>
    <tr>
      <td><%= link_to restaurant.name, restaurant %></td>
      <td><%= link_to 'Remove', restaurant, :method => :delete, :confirm => "Are you sure that you want to remove #{restaurant.name}?" %></td>
    </tr>
  <%- end %>
</table>

app/views/reservations/_form.html.erb
<%= form_for [@restaurant, @reservation] do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :request_time %>
    <%= f.date_field :request_time %>
  </div>
   <div>
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Update this reservation</h1>

<%= render 'form' %>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<% @reservations.each do |r| %>
  <p><%= r.restaurant.name %></p>
  <p><%= r.email %></p>
  <p><%= r.request_time  %></p>
  <p><%= r.message %></p>
<% end %>

<%= link_to 'Destroy', @restaurant, method: :delete, data: { confirm: 'Are you sure to delete?' } %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

app/views/reservations/new_reservation.html.erb
<h1> <%= @reservation.email %></h1>

app/views/reservations/show.html.erb
<h1><%= @reservation.restaurant.name %></h1>
<h2><%= @reservation.email %></h2>
<h2><%= @reservation.request_time %></h2>
<h2><%= @reservation.message %></h2>
<p><%= link_to "Edit", edit_restaurant_reservation_path(@restaurant, @reservation) %></p>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :full_address %><br>
    <%= f.text_field :full_address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <%= f.fields_for :reservations do |r| %>
     <%= r.object.request_time %>
     <%= r.select :status, %w(pending accepted declined) %>
     <hr />
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Full address</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.full_address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<H1> New Restaurants </h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.haml
%h1= @restaurant.name

- if (user_signed_in?) && (current_user == @restaurant.user)
  %p
    %strong
      user:
    = @restaurant.user.name
  %p
    %strong
      Dashboard:
    = link_to 'dashboard', dashboard_path

%p
  %strong
    Description:
  = @restaurant.description


%p
  %strong
    Full address:
  = @restaurant.full_address

%p
  %strong
    Phone number:
  = @restaurant.phone_number 

- if current_user != @restaurant.user
  = form_for([@restaurant, @reservation]) do |f| 
    %div
      = f.label :email
      = f.text_field :email

    %div
      = f.label :request_time
      = f.datetime_select :request_time

    %div
      = f.label :message
      = f.text_field :message

    %div
      = f.submit "Submit"

- if (user_signed_in?) && (current_user == @restaurant.user)
  %h1
    Reservation:
  %p
    - @restaurant.reservations.each do |r| 
      %p
        = r.email 
      %p
        = r.request_time 
      %p
        = r.message
      %form
      %label status
      %select.status  
        %option
          = r.status
          %input{:type => "submit", :value => "Update"}

= image_tag("https://maps.googleapis.com/maps/api/staticmap?center=#{@restaurant.full_address}&zoom=13&size=600x300&maptype=roadmap&markers=color:red%7C#{@restaurant.full_address}")

%br


- if (user_signed_in?) && (current_user == @restaurant.user)
  = link_to 'Edit', edit_restaurant_path 
  = link_to 'Destroy', @restaurant, method: :delete, data: { confirm: 'Are you sure to delete?' }

= link_to 'Back', restaurants_path 

app/views/users/dashboard.html.erb
<h1> <%= @user.name %> Dashboard </h1>
  <l> <%= link_to 'Add Restaurant', new_restaurant_path %>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  <%- @restaurants.each do |restaurant| %>
    <tr>
      <td><%= link_to restaurant.name, restaurant %></td>
      <td><%= link_to 'Remove', restaurant, :method => :delete, :confirm => "Are you sure that you want to remove #{restaurant.name}?" %></td>
    </tr>
  <%- end %>
</table>